// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx5xJ6nOhNxz33rgNvPR9b3Y8VAIkDmSE',
    appId: '1:813321513896:web:e4da142eeb965551b84b9d',
    messagingSenderId: '813321513896',
    projectId: 'rswaapps',
    authDomain: 'rswaapps.firebaseapp.com',
    storageBucket: 'rswaapps.firebasestorage.app',
    measurementId: 'G-W2YL32W260',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbbeJ9695vius5OZCSHjQID9wFL7t3g6E',
    appId: '1:813321513896:android:bf4fa015da8759d5b84b9d',
    messagingSenderId: '813321513896',
    projectId: 'rswaapps',
    storageBucket: 'rswaapps.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx5xJ6nOhNxz33rgNvPR9b3Y8VAIkDmSE',
    appId: '1:813321513896:web:7e041b318717b101b84b9d',
    messagingSenderId: '813321513896',
    projectId: 'rswaapps',
    authDomain: 'rswaapps.firebaseapp.com',
    storageBucket: 'rswaapps.firebasestorage.app',
    measurementId: 'G-X948K0C2TH',
  );
}
